### PR TITLE
[JENKINS-73939] Un-inline JavaScript in chart-setup.jelly

### PR DESCRIPTION
**Pull request by yaroslavafenkin**
[JENKINS-73939](https://issues.jenkins.io/browse/JENKINS-73939)

### Testing done
Tested against warnings-ng's PMD and CheckStyle.

https://www.loom.com/share/b6ee2a0732ce43e2af21ed5a6718a4ff?sid=1339b3bf-4076-4f88-91be-b5f22e316314

https://www.loom.com/share/ac5e2d4439374506b76ad9a8e85bac69?sid=6e1ca5df-dfc8-44c2-9f22-27c984be634d

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by uhafner — APPROVED** [review]
I installed the PR locally and the trend configuration button still works as expected. (Example configure button is in https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/main/178/maven-warnings/)

**Comment by nfalco79** [comment]
The version 5.5.1-2 that include this change cause the trend graph in build page a infinite loading loader
The error in console is:
```
Uncaught TypeError: ajaxProxy.getConfigurableBuildTrendModel is not a function
    renderAsynchronously http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:479
    renderConfigurableTrendChart http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:519
    <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:10
    <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:4
    EventListener.handleEvent* http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:1
echarts-api.js:479:23
```

https://issues.jenkins.io/browse/JENKINS-74775?filter=23848

**Comment by yaroslavafenkin** [comment]
> The version 5.5.1-2 that include this change cause the trend graph in build page a infinite loading loader The error in console is:
> 
> ```
> Uncaught TypeError: ajaxProxy.getConfigurableBuildTrendModel is not a function
>     renderAsynchronously http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:479
>     renderConfigurableTrendChart http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:519
>     <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:10
>     <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:4
>     EventListener.handleEvent* http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:1
> echarts-api.js:479:23
> ```
> 
> https://issues.jenkins.io/browse/JENKINS-74775?filter=23848

@nfalco79 you've assigned yourself to the JIRA ticket, does that imply you're working on the fix?

**Comment by nfalco79** [comment]
The issue in 5.5.1-3 version

**Comment by nfalco79** [comment]
> > The version 5.5.1-2 that include this change cause the trend graph in build page a infinite loading loader The error in console is:
> > ```
> > Uncaught TypeError: ajaxProxy.getConfigurableBuildTrendModel is not a function
> >     renderAsynchronously http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:479
> >     renderConfigurableTrendChart http://localhost:8090/jenkins/static/afdc740e/plugin/echarts-api/js/echarts-api.js:519
> >     <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:10
> >     <anonymous> http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:4
> >     EventListener.handleEvent* http://localhost:8090/jenkins/adjuncts/afdc740e/io/jenkins/plugins/echarts/render-configurable-trend-chart.js:1
> > echarts-api.js:479:23
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://issues.jenkins.io/browse/JENKINS-74775?filter=23848
> 
> @nfalco79 you've assigned yourself to the JIRA ticket, does that imply you're working on the fix?

No, I was investigating, the reported suggestion didn't work, so I was here to report the problem.

**Comment by yaroslavafenkin** [comment]
Looking at the stack trace it's rather caused by https://github.com/jenkinsci/echarts-api-plugin/pull/357
